# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpa.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpa.proto\x12\x03rpa\"F\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x13\n\x0bparams_json\x18\x03 \x01(\t\"C\n\x0cTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\r\n\x0bPingRequest\"6\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x01\x32m\n\nRPAService\x12\x32\n\x0b\x45xecuteTask\x12\x10.rpa.TaskRequest\x1a\x11.rpa.TaskResponse\x12+\n\x04Ping\x12\x10.rpa.PingRequest\x1a\x11.rpa.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=18
  _globals['_TASKREQUEST']._serialized_end=88
  _globals['_TASKRESPONSE']._serialized_start=90
  _globals['_TASKRESPONSE']._serialized_end=157
  _globals['_PINGREQUEST']._serialized_start=159
  _globals['_PINGREQUEST']._serialized_end=172
  _globals['_PINGRESPONSE']._serialized_start=174
  _globals['_PINGRESPONSE']._serialized_end=228
  _globals['_RPASERVICE']._serialized_start=230
  _globals['_RPASERVICE']._serialized_end=339
# @@protoc_insertion_point(module_scope)
